pub const NON_MONOTONIC_TIME: felt252 = 'NON_MONOTONIC_TIME';
pub const STALE_TIME: felt252 = 'STALE_TIME';
pub const ALREADY_INITIALIZED: felt252 = 'ALREADY_INITIALIZED';
pub const TIMESTAMP_TOO_OLD: felt252 = 'TIMESTAMP_TOO_OLD';
