use starkware_utils::errors::{Describable, ErrorDisplay};

#[derive(Drop)]
pub enum Error {
    // Simple error constants
    ALREADY_INITIALIZED,
    CANCELLETION_TIME_PASSED,
    CANT_DEPOSIT_SYNTHETIC,
    DEPOSITOR_NOT_PERPS_ADDRESS,
    DEPOSITOR_NOT_CALLER_ADDRESS,
    DEPOSIT_ALREADY_CANCELED,
    DEPOSIT_ALREADY_PROCESSED,
    DEPOSIT_ALREADY_REGISTERED,
    DEPOSIT_NOT_CANCELABLE,
    DEPOSIT_NOT_REGISTERED,
    INVALID_CANCEL_DELAY,
    TRANSFER_FAILED,
    ZERO_AMOUNT,
}

impl DescribableError of Describable<Error> {
    fn describe(self: @Error) -> ByteArray {
        match self {
            // Simple error constants
            Error::ALREADY_INITIALIZED => "ALREADY_INITIALIZED",
            Error::CANCELLETION_TIME_PASSED => "CANCELLETION_TIME_PASSED",
            Error::CANT_DEPOSIT_SYNTHETIC => "CANT_DEPOSIT_SYNTHETIC",
            Error::DEPOSITOR_NOT_PERPS_ADDRESS => "DEPOSITOR_NOT_PERPS_ADDRESS",
            Error::DEPOSITOR_NOT_CALLER_ADDRESS => "DEPOSITOR_NOT_CALLER_ADDRESS",
            Error::DEPOSIT_ALREADY_CANCELED => "DEPOSIT_ALREADY_CANCELED",
            Error::DEPOSIT_ALREADY_PROCESSED => "DEPOSIT_ALREADY_PROCESSED",
            Error::DEPOSIT_ALREADY_REGISTERED => "DEPOSIT_ALREADY_REGISTERED",
            Error::DEPOSIT_NOT_CANCELABLE => "DEPOSIT_NOT_CANCELABLE",
            Error::DEPOSIT_NOT_REGISTERED => "DEPOSIT_NOT_REGISTERED",
            Error::INVALID_CANCEL_DELAY => "INVALID_CANCEL_DELAY",
            Error::TRANSFER_FAILED => "TRANSFER_FAILED",
            Error::ZERO_AMOUNT => "ZERO_AMOUNT",
        }
    }
}
